### ISSUE TITLE
1.8.1版本上一打开就出错

### ISSUE THREAD

**Issue by WenhaiLin** [shpz/CreatorClean#1]
TypeError: Cannot read property '__uuid__' of null
    at Vue.searchClip  (/Users/xxxxx/.CocosCreator/packages/CreatorClean/panel/panel.js:141:57)
    at Vue.searchClip (app://bower_components/vue/dist/vue.js:220:27)
    at eval  (/Users/xxxxx/.CocosCreator/packages/CreatorClean/panel/panel.js:68:42)
    at Array.forEach (native)
    at eval  (/Users/xxxxx/.CocosCreator/packages/CreatorClean/panel/panel.js:65:33)
    at Array.forEach (native)
    at callback  (/Users/xxxxx/.CocosCreator/packages/CreatorClean/panel/panel.js:58:26)
    at eval  (/Users/xxxxx/.CocosCreator/packages/CreatorClean/panel/panel.js:99:29)
    at EventEmitter.ipcRenderer.on.n (/Applications/CocosCreator  1.8.1.app/Contents/Resources/app.asar/editor-framework/lib/renderer/ipc.js:1:4493)
    at emitMany  (events.js:127:13)

属性检查器
TypeError: Cannot read property '__uuid__' of null

**Comment by shpz** [comment]
这个问题解决了吧，好像论坛上有人给我提过
